<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Charan" failures="2" tests="9" name="retrying falied testcases" time="0.128" errors="0" timestamp="2021-11-13T15:28:43 IST">
  <testcase classname="testNgframework.FirstProject" name="Test1" time="0.008"/>
  <testcase classname="testNgframework.FirstProject" name="Test2" time="0.006">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="testNgframework.FirstProject" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="testNgframework.FirstProject" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="testNgframework.FirstProject" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNgframework.FirstProject.Test2(FirstProject.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="testNgframework.FirstProject" name="Test" time="0.002">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="testNgframework.FirstProject" name="Test" time="0.001">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="testNgframework.FirstProject" name="Test" time="0.005">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="testNgframework.FirstProject" name="Test" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNgframework.FirstProject.Test(FirstProject.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
</testsuite> <!-- retrying falied testcases -->
